name: Release (Latest)

on:
  push:
    branches:
      - main
      - workflows
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest # macOS is needed for iOS builds

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Delete old "latest" release (if exists)
        run: |
          gh release delete latest -y || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create "latest" release
        run: |
          gh release create latest \
            --title "Latest Build" \
            --notes "Automatic release from main push" \
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
