name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # macOS is needed for iOS builds
    env:
      SERVER_URL: localhost
    
    defaults:
      run:
        working-directory: ./scouts_finances_flutter

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Style check
        run: flutter analyze

      - name: Build Android APK
        run: flutter build apk --release
    
      - name: Build iOS App
        run: flutter build ios --release --no-codesign